### ISSUE TITLE
Adjust existing color settings and add more

### ISSUE THREAD

**Issue by fjarrett** [LiftUX/ascension-theme#18]
- [x] Rename the existing **Header Text Color** to be **Tagline Text Color** (`#545454`).
- [x] Create an additional setting named **Header Text Color** (`#ffffff`) that controls the text color overlaying the **Header Image**.
- [x] Add a color setting for **Main Text Color** (`#212121`).
- [x] Add a color setting for **Secondary Text Color** (`#194f6e`).
- [x] Add a color setting for **Link Text Color** (`#39baf3`).
- [x] Add a **Color Scheme** selector (like Twenty Sixteen does) with 5 or 6 options.

**Comment by chriswallace** [comment]
@schrapel For the color schemes, we want to implement them the way [Twenty Sixteen does](https://github.com/WordPress/twentysixteen/blob/master/inc/customizer.php). Let's work towards a similar solution for color schemes there.

**Comment by schrapel** [comment]
For this I have basically removed customizer stuff from the child and parent theme, then replaced with twenty sixteen customzier component which I will extend to meet everything here. Didn't make sense to start fresh

**Comment by fjarrett** [comment]
@schrapel Looking forward to seeing this!

**Comment by schrapel** [comment]
On a side note I created a new setting for **Tagline Text Color** instead of renaming as **Header Text Color** as it's part of `add_theme_support('custom-header)` and it didn't make sense to do it how you suggested. Obviously end functionality will be the same

**Comment by schrapel** [comment]
Everything in working in the customizer. I just need to go through the style.css and take out the classes/id for each element in the color scheme.

I left all the namespacing as twentysixteen. Do you want me to change everything to basis?

**Comment by fjarrett** [comment]
@schrapel Cool, let me know when you've got the CSS targets in for each color and I will test this out.

For namespacing, everything needs to be `primer`. See #32.

**Comment by schrapel** [comment]
I was trying to be really clever by writing some code that would parse a stylesheet and grab out all the selectors needed for the stylesheet but turns out there are so many edge cases and different ways colors are used. I'll just do it manually here to save time but I thought it was a good idea if we have 10 themes to do this for

**Comment by fjarrett** [comment]
Yeah this sounds like a great idea in theory, but perhaps not in practice.
